### PR TITLE
Updates from Flask 0.11, fixes #15

### LINKED ISSUE #15: global: integrate latest changes from flask
```
9594876 Added plugin support to the cli
a7d829c Update docs to the new CLI patterns
523e271 Implemented simplified CLI interface
```

also seems like this will land on v0.11 so references to 1.0 should be removed, and hopefully as soon as v0.11 is released we can deprecate this module.

### PR DESCRIPTION
**Pull request by jezdez**
This backports:
- https://github.com/pallets/flask/commit/523e27118359425048541d92892f20ee048c0b76
- https://github.com/pallets/flask/commit/a7d829c61854bc609a343eec114d2a129761fe9f
- https://github.com/pallets/flask/commit/9594876c1f6377a3f8b911d31e8c941295baa281
- https://github.com/pallets/flask/commit/a72583652329da810fc2a04e8541a0e2efd47ee1
- https://github.com/pallets/flask/commit/6bee3e4995066466a35ac080844d4962a728d084
- https://github.com/pallets/flask/commit/6b28ceba83c3b76eea2e5a89327318af67404298
- https://github.com/pallets/flask/commit/fe5f714026b68b1416c3d3985bce5063901c320f

It also removes Python 2.6 from the Tox config and adds Python 3.5.

### CODE REVIEW

**Comment by tiborsimko** [comment]
@lnielsen Please don't forget next time to amend commits before merging in order to respect our [kwalitee](https://github.com/inveniosoftware/kwalitee) conventions.

**Comment by jezdez** [comment]
@tiborsimko Anything I should make sure next time I contribute?

**Comment by tiborsimko** [comment]
@jezdez We should actually plug the kwalitee checks into Travis CI, in that way they'll be run automatically.  It is basically a collection of cosmetic checks regarding not only PEP8/PEP257, but also regarding commit message formatting, the purpose being the automatic generation of release notes from appropriately formatted messages.  I'm updating the kwalitee docs these days, because they are a bit outdated. I'll reply back when done, in case you are interested...

**Comment by jezdez** [comment]
@tiborsimko Sounds sensible, I've done similar things before with flake8 and pydocstyle (neé pep257) before 👍

**Comment by lnielsen** [comment]
I honestly prefer to leave the original Flask commit message as it was done. It makes it much easier to identify which commits have been migrated and which hasn't.

**Pull request merged**
