### PR TITLE
Make sure the parameter passed to the CLI's AppGroup is the app's name, not the app itself.

### PR DESCRIPTION
**Pull request by jezdez**
This is bascially a backport of https://github.com/pallets/flask/pull/1806 and should only be merged once that has landed.

### CODE REVIEW

**Comment by lnielsen** [comment]
Thanks. We'll keep an eye on the Flask PR.

**Comment by jezdez** [comment]
@lnielsen The patch was merged upstream FWIW

**Comment by lnielsen** [comment]
Thanks - tests are failing with the latest package development versions on all Python versions (https://github.com/inveniosoftware/flask-cli/blob/master/requirements.devel.txt) - can you take a look?

**Comment by jezdez** [comment]
@lnielsen I just needed to force-push the branch again to restart the tests. The tests that were failing use the current development version of Flask as a requirement which didn't at the time of the test run have the changes needed for this to pass. Since Flask-CLI tries to import `flask.cli` in its `__init__.py` for future compatibility this can be filed as red herring.

**Pull request merged**
