### PR TITLE
release: v0.3.0

### PR DESCRIPTION
**Pull request by lnielsen**

### CODE REVIEW

**Comment by tiborsimko** [comment]
It would be good to amend the commit message to introduce `AMENDS` so that the release notes can be auto-generated.  Otherwise nothing is produced right now:

```
$ kwalitee prepare release v0.2.1..
```

This may come handy when we get to creating information-rich inveniosoftware.org web site dashboard.

**Comment by lnielsen** [comment]
@tiborsimko It won't help for this release, since previous commits also didn't use the style. We can fix it for future releases.

**Comment by tiborsimko** [comment]
@lnielsen It would help since you can put several AMENDS in a row, see live example of e.g. Invenio 2.0.4 release notes (`git log acf26cdeea82c4af39b157fe96a9be5c4f82c72f..v2.0.4`) or IIRC the worst case we had for Invenio 2.1.0 release notes (`git log 12fb10bcc399922866e3565d26846c19e8cc062f..v2.1.0`).

**Comment by jezdez** [comment]
Thanks for the release all!

**Pull request merged**
